#!/bin/bash
STARTOFSCRIPT=$(date)
MYUSERNAME="${VARIABLE:-default}"
MYPASSWORD="${VARIABLE:-default}"
echo "MYUSERNAME: $MYUSERNAME"
echo "MYPASSWORD: $MYPASSWORD"
echo "STARTOFSCRIPT: $STARTOFSCRIPT"
sleep 10
ENDOFSCRIPT=$(date)
echo "ENDOFSCRIPT: $ENDOFSCRIPT"
